- name: install Docker compose on EC2 instance
  hosts: EC2
  become: yes
  vars:
    docker_install_compose: true
   # docker_compose_version: "2.20.2"
  roles:
    - geerlingguy.docker
    - deploy_petclinic
